version: '3.4'

services:
  one-api:
    image: justsong/one-api:latest
    container_name: one-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "0.0.0.0:3793:3000"
    volumes:
      - /mnt/ssd_pool/data/one-api/data:/data
      - /mnt/ssd_pool/data/one-api/logs:/app/logs
    environment:
      - SQLITE_PATH=/data/one-api.db
      - SESSION_SECRET=18f463cff163ab06fca1bfa6287f30d1f83bbb581c978d0c56be7dd5aea86a50
      - TZ=Asia/Shanghai
